packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  esbuild: true
  msgpackr-extract: false
  prisma: true
  unrs-resolver: true
  workerd: false
